### ISSUE TITLE
Issue: InternalOpenIDError: Failed to verify assertion

### ISSUE THREAD

**Issue by aidenwallis** [havard/node-openid#142]
I'm using passport-steam, which using passport-openid, which after chasing through the code I am positive it links into this library. I really need this authentication to work, it happens on the callback, using MySQL as the database however I don't think that this is the issue.

`InternalOpenIDError: Failed to verify assertion
    at /home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/lib/passport-openid/strategy.js:184:36
    at /home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:927:12
    at /home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:1051:16
    at /home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:1169:16
    at Request._callback (/home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/openid.js:190:7)
    at Request.self.callback (/home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/admin/csgo_raptor/node_modules/passport-steam/node_modules/passport-openid/node_modules/openid/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)`

**Comment by havard** [comment]
Steam authentication works fine using just node-openid (provided their requirements of using stateless verification and specifying a realm are met). This is a passport error, please contact them.

**Comment by aidenwallis** [comment]
Okay, sorry for the bother, I will do that now!
